menu_items = [  
# Starters - Veg
    {"id": "s_v_1", "category": "Starters - Veg", "item_name": "Veg Noodles (6 Pcs)", "price": 65, "image": "starter veg veg nuggets.png", "description": "Classic noodles, sautéed with fresh vegetables and aromatic spices."},
    {"id": "s_v_2", "category": "Starters - Veg", "item_name": "Veg Momos (5 Pcs)", "price": 65, "image": "momos veg momos.png", "description": "Steamed dumplings filled with seasoned vegetables."},
    {"id": "s_v_3", "category": "Starters - Veg", "item_name": "Corn Cheese Ball (5 Pcs)", "price": 80, "image": "starter veg corn cheese ball.png", "description": "Crispy fried balls with sweet corn and melted cheese."},
    {"id": "s_v_4", "category": "Starters - Veg", "item_name": "Corn Cheese Nuggets (5 Pcs)", "price": 80, "image": "starter veg potato cheese ball.png", "description": "Golden nuggets bursting with corn and cheese flavor."},
    {"id": "s_v_5", "category": "Starters - Veg", "item_name": "Veg Lollipop (3 Pcs)", "price": 100, "image": "starter veg smiley fries.png", "description": "Vegetable fritters shaped like lollipops, crispy and savory."},
    # Starters - Non-Veg
    {"id": "s_nv_1", "category": "Starters - Non-Veg", "item_name": "Chicken Lollipop (3 Pcs)", "price": 120, "image": "fried chicken chicken lollypop.png", "description": "Juicy chicken drumettes, deep-fried to perfection."},
    {"id": "s_nv_2", "category": "Starters - Non-Veg", "item_name": "Chicken Strips (4 Pcs)", "price": 100, "image": "fried chicken chicken strips.png", "description": "Tender chicken strips, lightly breaded and fried."},
    {"id": "s_nv_3", "category": "Starters - Non-Veg", "item_name": "Chicken Wings (4 Pcs)", "price": 120, "image": "fried chicken chicken pop corn.png", "description": "Crispy chicken wings, seasoned and fried."},
    {"id": "s_nv_4", "category": "Starters - Non-Veg", "item_name": "Chicken Crispy", "price": 130, "image": "fried chicken crispey fried chicken.png", "description": "Crispy fried chicken, a perfect appetizer."},
    # Momos - Veg
    {"id": "m_v_1", "category": "Momos - Veg", "item_name": "Panner Momos (5 Pcs)", "price": 70, "image": "momos veg paneer momos.png", "description": "Steamed Panner Filled Momos."},
    {"id": "m_v_2", "category": "Momos - Veg", "item_name": "Veg Momos (4 Pcs)", "price": 65, "image": "momos veg momos.png", "description": "Steamed dumplings filled with seasoned vegetables."},
    # Momos - Non-Veg
    {"id": "m_nv_1", "category": "Momos - Non-Veg", "item_name": "Chicken Momos", "price": 85, "image": "momos non veg chicken momos.png", "description": "Steamed dumplings filled with juicy chicken."},
    {"id": "m_nv_2", "category": "Momos - Non-Veg", "item_name": "Peri Peri Momos", "price": 90, "image": "momos non veg chicken momos.png", "description": "Spicy peri peri flavored chicken momos."},
    # Sandwich - Veg
    {"id": "s_v_s_1", "category": "Sandwich - Veg", "item_name": "Veg Cheese Sandwich", "price": 65, "image": "sandwitch veg cheese sandwitch.png", "description": "Grilled sandwich with fresh vegetables and cheese."},
    {"id": "s_v_s_2", "category": "Sandwich - Veg", "item_name": "Paneer Sandwich", "price": 70, "image": "sandwitch veg paneer sandwitch.png", "description": "Toasted sandwich with flavorful paneer filling."},
    {"id": "s_v_s_3", "category": "Sandwich - Veg", "item_name": "Bombay Veg Sandwich", "price": 75, "image": "sandwitch veg veg sandwitch.png", "description": "Spicy Bombay-style vegetable sandwich."},
    # Sandwich - Non-Veg
    {"id": "s_nv_s_1", "category": "Sandwich - Non-Veg", "item_name": "Chicken Sandwich", "price": 80, "image": "sandwitch non veg chicken sandwitch.png", "description": "Classic sandwich with shredded chicken filling."},
    {"id": "s_nv_s_2", "category": "Sandwich - Non-Veg", "item_name": "Chicken Cheese Sandwich", "price": 90, "image": "sandwitch non veg chicken tikka sandwitch.png", "description": "Chicken sandwich with melted cheese."},
    {"id": "s_nv_s_3", "category": "Sandwich - Non-Veg", "item_name": "BBQ Chicken Sandwich", "price": 90, "image": "sandwitch non veg BBQ chicken sandwitch.png", "description": "Tangy BBQ chicken in a grilled sandwich."},
    {"id": "s_nv_s_4", "category": "Sandwich - Non-Veg", "item_name": "Bombay Chicken Sandwich", "price": 95, "image": "sandwitch non veg peri peri chicken sandwitch.png", "description": "Spicy Bombay-style chicken sandwich."},
    # Wraps - Veg
    {"id": "w_v_1", "category": "Wrap - Veg", "item_name": "Veg Wrap", "price": 60, "image": "wrap veg veg wrap.png", "description": "Fresh vegetables wrapped in a soft tortilla."},
    {"id": "w_v_2", "category": "Wrap - Veg", "item_name": "Paneer Wrap", "price": 80, "image": "wrap veg paneer wrap.png", "description": "Spiced paneer wrapped in a soft tortilla."},
    # Wraps - Non-Veg
    {"id": "w_nv_1", "category": "Wrap - Non-Veg", "item_name": "Chicken Tikka Wrap", "price": 80, "image": "wrap non veg chicken tikka wrap.png", "description": "Spicy chicken tikka wrapped in a tortilla."},
    {"id": "w_nv_2", "category": "Wrap - Non-Veg", "item_name": "Peri Peri Wrap", "price": 80, "image": "wrap non veg peri peri wrap.png", "description": "Fiery peri peri chicken wrapped in a tortilla."},
    {"id": "w_nv_3", "category": "Wrap - Non-Veg", "item_name": "BBQ Chicken Wrap", "price": 85, "image": "wrap non veg BBQ chicken wrap.png", "description": "Smoky BBQ chicken wrapped in a tortilla."},
    # Burger
    {"id": "b_1", "category": "Burger", "item_name": "Veg Burger", "price": 80, "image": "burger veg burger.png", "description": "Classic veggie patty burger."},
    {"id": "b_2", "category": "Burger", "item_name": "Paneer Burger", "price": 90, "image": "burgur paneer burgur.png", "description": "Paneer patty burger with spices."},
    {"id": "b_3", "category": "Burger", "item_name": "Chicken Burger", "price": 100, "image": "burger chicken burger.png", "description": "Juicy chicken patty burger."},
    # Pizza - Veg
    {"id": "p_v_1", "category": "Pizza - Veg", "item_name": "Veg Pizza", "price": 100, "image": "pizza veg veg pizza.png", "description": "Classic vegetable topping pizza."},
    {"id": "p_v_2", "category": "Pizza - Veg", "item_name": "Paneer Pizza", "price": 120, "image": "pizza veg paneer pizza.png", "description": "Paneer and veggie pizza."},
    {"id": "p_v_3", "category": "Pizza - Veg", "item_name": "Peri Peri Paneer Pizza", "price": 130, "image": "pizza veg peri peri paneer pizza.png", "description": "Spicy peri peri paneer pizza."},
    {"id": "p_v_4", "category": "Pizza - Veg", "item_name": "Corn Pizza", "price": 110, "image": "pizza veg corn pizza.png", "description": "Sweet corn topping pizza."},
    # Pizza - Non-Veg
    {"id": "p_nv_1", "category": "Pizza - Non-Veg", "item_name": "Chicken Tikka Pizza", "price": 130, "image": "pizza non veg chicken tikka pizza.png", "description": "Pizza topped with spicy chicken tikka."},
    {"id": "p_nv_2", "category": "Pizza - Non-Veg", "item_name": "Peri Peri Chicken Pizza", "price": 140, "image": "pizza non veg peri peri chicken pizza.png", "description": "Pizza with peri peri chicken pieces."},
    {"id": "p_nv_3", "category": "Pizza - Non-Veg", "item_name": "BBQ Chicken Pizza", "price": 140, "image": "pizza non veg BBQ chicken pizza.png", "description": "Pizza with BBQ chicken topping."},
    {"id": "p_nv_4", "category": "Pizza - Non-Veg", "item_name": "Chicken Golden Pizza", "price": 150, "image": "pizza non veg peri peri chicken pizza.png", "description": "Rich golden chicken pizza, a delightful treat."},
    # Dessert & Ice Cream
    {"id": "d_1", "category": "Dessert", "item_name": "Sizzling Brownie", "price": 120, "image": "dessert sizzling brownie.png", "description": "Hot sizzling brownie with ice cream."},
    {"id": "d_2", "category": "Dessert", "item_name": "Royalrich Falooda", "price": 110, "image": "dessert royalrich falooda.png", "description": "Royalrich falooda with dry fruits."},
    {"id": "d_3", "category": "Dessert", "item_name": "Falooda Gold", "price": 120, "image": "dessert falooda gold.png", "description": "Golden falooda with rich flavors."},
    {"id": "d_4", "category": "Dessert", "item_name": "Dry Fruit Falooda", "price": 130, "image": "dessert dry fruit falooda.png", "description": "Falooda with dry fruits."},
    {"id": "d_5", "category": "Dessert", "item_name": "Brownie with Ice Cream", "price": 140, "image": "dessert brownie with ice cream.png", "description": "Brownie served with ice cream."},
    # Ice Cream (Single Scoop)
    {"id": "ic_ss_1", "category": "Ice Cream (Single Scoop)", "item_name": "Vanilla", "price": 40, "image": "ice cream vanilla ice cream.png", "description": "Classic vanilla ice cream."},
    {"id": "ic_ss_2", "category": "Ice Cream (Single Scoop)", "item_name": "Chocolate", "price": 40, "image": "ice cream chpcolate icecream.png", "description": "Rich chocolate ice cream."},
    {"id": "ic_ss_3", "category": "Ice Cream (Single Scoop)", "item_name": "Butter Scotch", "price": 40, "image": "icecream scoop butter scotch.png", "description": "Creamy butterscotch ice cream."},
    {"id": "ic_ss_4", "category": "Ice Cream (Single Scoop)", "item_name": "Strawberry", "price": 40, "image": "ice cream strawberry.png", "description": "Fresh strawberry ice cream."},
    {"id": "ic_ss_5", "category": "Ice Cream (Single Scoop)", "item_name": "Black Currant", "price": 40, "image": "ice cream black currant.png", "description": "Black currant ice cream."},
    {"id": "ic_ss_6", "category": "Ice Cream (Single Scoop)", "item_name": "Tender Coconut", "price": 40, "image": "ice cream tender coconut.png", "description": "Tender coconut ice cream."},
    # Milkshake
    {"id": "ms_1", "category": "Milkshake", "item_name": "Tender Coconut Milkshake", "price": 70, "image": "Milkshake tender coconut shake.png", "description": "Refreshing milkshake made with tender coconut."},
    {"id": "ms_2", "category": "Milkshake", "item_name": "Strawberry Milkshake", "price": 70, "image": "Milkshake strawberry.png", "description": "Sweet strawberry milkshake."},
    {"id": "ms_3", "category": "Milkshake", "item_name": "Oreo Milkshake", "price": 80, "image": "Milkshake oreo.png", "description": "Oreo cookie milkshake."},
    {"id": "ms_4", "category": "Milkshake", "item_name": "Mango Milkshake", "price": 80, "image": "Milkshake mango.png", "description": "Mango flavored milkshake."},
    {"id": "ms_5", "category": "Milkshake", "item_name": "Kitkat Milkshake", "price": 80, "image": "Milkshake kitkat.png", "description": "Kitkat chocolate milkshake."},
    {"id": "ms_6", "category": "Milkshake", "item_name": "Chocolate Milkshake", "price": 80, "image": "Milkshake chocolate.png", "description": "Rich chocolate milkshake."},
    {"id": "ms_7", "category": "Milkshake", "item_name": "Butter Scotch Milkshake", "price": 80, "image": "Milkshake butter scotch.png", "description": "Butterscotch flavored milkshake."},
    {"id": "ms_8", "category": "Milkshake", "item_name": "Black Currant Milkshake", "price": 80, "image": "Milkshake black currant.png", "description": "Black currant flavored milkshake."},
    {"id": "ms_9", "category": "Milkshake", "item_name": "Apple Shake", "price": 80, "image": "fresh juice  apple juice.png", "description": "Refreshing apple flavored milkshake."},
    # Fresh Juice
    {"id": "fj_1", "category": "Fresh Juice", "item_name": "Orange Juice", "price": 75, "image": "fresh juice  orange juice.png", "description": "Freshly squeezed orange juice."},
    {"id": "fj_2", "category": "Fresh Juice", "item_name": "Apple Juice", "price": 80, "image": "fresh juice  apple juice.png", "description": "Fresh apple juice."},
    {"id": "fj_3", "category": "Fresh Juice", "item_name": "Pineapple Juice", "price": 80, "image": "fresh juice  pineapple.png", "description": "Fresh pineapple juice."},
    {"id": "fj_4", "category": "Fresh Juice", "item_name": "Watermelon Juice", "price": 70, "image": "fresh juice  watermelon.png", "description": "Fresh watermelon juice."},
    {"id": "fj_5", "category": "Fresh Juice", "item_name": "Mosambi Juice", "price": 80, "image": "fresh juice  mosambi.png", "description": "Fresh mosambi (sweet lime) juice."},
    {"id": "fj_6", "category": "Fresh Juice", "item_name": "Musk Melon Juice", "price": 80, "image": "fresh juice musk melon.png", "description": "Fresh musk melon juice."},
    {"id": "fj_7", "category": "Fresh Juice", "item_name": "Pomegranate Juice", "price": 90, "image": "fresh juice  pomegranate.png", "description": "Fresh pomegranate juice."},
    # Mojito
    {"id": "mj_1", "category": "Mojito", "item_name": "Tea", "price": 12, "image": "Mojito tea.png", "description": "Classic hot tea."},
    {"id": "mj_2", "category": "Mojito", "item_name": "Masala Tea", "price": 15, "image": "Mojito masala tea.png", "description": "Spiced masala tea."},
    {"id": "mj_3", "category": "Mojito", "item_name": "Lemon Tea", "price": 15, "image": "Mojito lemon tea.png", "description": "Refreshing lemon tea."},
    {"id": "mj_4", "category": "Mojito", "item_name": "Green Tea", "price": 20, "image": "Mojito green tea.png", "description": "Healthy green tea."},
    {"id": "mj_5", "category": "Mojito", "item_name": "Black Tea", "price": 15, "image": "Mojito black tea.png", "description": "Classic black tea."},
    {"id": "mj_6", "category": "Mojito", "item_name": "Filter Coffee", "price": 20, "image": "Mojito filter coffee.png", "description": "South Indian filter coffee."},
    {"id": "mj_7", "category": "Mojito", "item_name": "Sukku Malli Coffee", "price": 20, "image": "Mojito sukku malli cofee.png", "description": "Herbal sukku malli coffee."},
    {"id": "mj_8", "category": "Mojito", "item_name": "Nattu Sakkarai Coffee", "price": 20, "image": "Mojito nattu sakarai coffee.png", "description": "Coffee with country sugar."},
    {"id": "mj_9", "category": "Mojito", "item_name": "Nattu Sakkarai Tea", "price": 15, "image": "Mojito nattu sakarai tea.png", "description": "Tea with country sugar."},
    {"id": "mj_10", "category": "Mojito", "item_name": "Nattu Sakkarai Milk", "price": 20, "image": "Mojito nattu sakarai milk.png", "description": "Milk with country sugar."},
    {"id": "mj_11", "category": "Mojito", "item_name": "Panagarkandu Milk", "price": 20, "image": "Mojito panagarkandu milk.png", "description": "Milk with palm sugar."},
    {"id": "mj_12", "category": "Mojito", "item_name": "Pepper Milk", "price": 20, "image": "Mojito pepper milk.png", "description": "Spiced pepper milk."},
    {"id": "mj_13", "category": "Mojito", "item_name": "Badam Milk (Hot)", "price": 30, "image": "Mojito badam milk hot.png", "description": "Hot almond milk."},
    {"id": "mj_14", "category": "Mojito", "item_name": "Blue Mint Mojito", "price": 40, "image": "Mojito blue mint.png", "description": "Cool blue mint mojito."},
    {"id": "mj_15", "category": "Mojito", "item_name": "Blueberry Mojito", "price": 40, "image": "Mojito blue berry.png", "description": "Fruity blueberry mojito."},
    {"id": "mj_16", "category": "Mojito", "item_name": "Kiwi Mojito", "price": 40, "image": "Mojito kiwi.png", "description": "Tangy kiwi mojito."},
    {"id": "mj_17", "category": "Mojito", "item_name": "Green Apple Mojito", "price": 40, "image": "Mojito green apple.png", "description": "Crisp green apple mojito."},
    {"id": "mj_18", "category": "Mojito", "item_name": "Pineapple Mojito", "price": 40, "image": "Mojito pineapple.png", "description": "Pineapple flavored mojito."},
    {"id": "mj_19", "category": "Mojito", "item_name": "Ginger Lime Mojito", "price": 40, "image": "Mojito ginger lime.png", "description": "Ginger and lime mojito."},
    {"id": "mj_20", "category": "Mojito", "item_name": "Fresh Lime Soda", "price": 30, "image": "Mojito fresh lime soda.png", "description": "Fresh lime soda."},
    # Combos
    {"id": "c_1", "category": "Combos", "item_name": "Combo 1: Veg Sandwich + Veg Wrap + Mojito", "price": 199, "image": "combo 1.png", "description": "A delightful combo of Veg Sandwich, Veg Wrap, and a refreshing Mojito."},
    {"id": "c_2", "category": "Combos", "item_name": "Combo 2: Chicken Burger + Fries + Milkshake", "price": 249, "image": "combo 2.png", "description": "Chicken Burger, crispy fries, and a milkshake."},
    {"id": "c_3", "category": "Combos", "item_name": "Combo 3: Paneer Pizza + Brownie + Mojito", "price": 299, "image": "combo 3.png", "description": "Paneer Pizza, Brownie, and a Mojito."},
    {"id": "c_4", "category": "Combos", "item_name": "Combo 4: Chicken Tikka Wrap + Peri Peri Fries + Blueberry Mojito", "price": 279, "image": "combo 4.png", "description": "Chicken Tikka Wrap, Peri Peri Fries, and Blueberry Mojito."},
]